language: ruby

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-2.0.0
  - rbx-2.1.1
  - ree

jdk:
  - oraclejdk7
  - openjdk7

env: CI="travis"

notifications:
  email: false
  flowdock: 1da4416b8ff98d1880986472428b1b1b

branches:
  only:
    - master
    - 2.x-stable

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2.0.0
    - rvm: rbx-2.1.1
  exclude:
    - rvm: 1.8.7
      jdk: openjdk7
      env: CI="travis"
    - rvm: 1.9.2
      jdk: openjdk7
      env: CI="travis"
    - rvm: 1.9.3
      jdk: openjdk7
      env: CI="travis"
    - rvm: 2.0.0
      jdk: openjdk7
      env: CI="travis"
    - rvm: 2.1.0
      jdk: openjdk7
      env: CI="travis"
    - rvm: ruby-head
      jdk: openjdk7
      env: CI="travis"
    - rvm: ree
      jdk: openjdk7
      env: CI="travis"
    - rvm: rbx-2.0.0
      jdk: openjdk7
      env: CI="travis"
    - rvm: rbx-2.1.1
      jdk: openjdk7
      env: CI="travis"
